// frontend-react/src/components/Map.tsx
import React, { useEffect, useState } from 'react';
import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet';
import L from 'leaflet';
import '../styles/Map.css';
import { fetchLocations, Locations } from '../services/api';
import ImageGallery from './ImageGallery';

interface MapProps {
    onSelectImage: (imageUrl: string) => void;
}

const Map: React.FC<MapProps> = ({ onSelectImage }) => {
    const [locations, setLocations] = useState<Locations>({});
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const loadLocations = async () => {
            try {
                const data = await fetchLocations();
                setLocations(data);
                setLoading(false);
            } catch (err) {
                console.error('Failed to load locations:', err);
                setError('Failed to load map data');
                setLoading(false);
            }
        };

        loadLocations();
    }, []);

    const pinIcon = L.divIcon({
        className: 'emoji-pin',
        html: '📍', 
        iconSize: [30, 30],
        iconAnchor: [15, 30]
    });

    if (loading) {
        return <div style={{ color: 'white', textAlign: 'center', paddingTop: '50px' }}>Loading map...</div>;
    }

    if (error) {
        return <div style={{ color: 'white', textAlign: 'center', paddingTop: '50px' }}>Error: {error}</div>;
    }

    return (
        <MapContainer 
            center={[30, 0]} 
            zoom={2} 
            minZoom={2} 
            maxZoom={6}
            id="map"
        >
            <TileLayer
                url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"
                attribution="&copy; <a href='https://carto.com/'>Carto</a>"
                noWrap={true}
            />
            {Object.entries(locations).map(([region, { Lat, Long }]) => (
                <Marker 
                    key={region} 
                    position={[Lat, Long]} 
                    icon={pinIcon}
                >
                    <Popup maxWidth={800}>
                        <ImageGallery 
                            region={region} 
                            onSelectImage={onSelectImage} 
                        />
                    </Popup>
                </Marker>
            ))}
        </MapContainer>
    );
};

export default Map;

// frontend/src/lib/Map.svelte
<script>
	import { Map, TileLayer, Marker, Popup, DivIcon } from 'sveaflet';
    import { fetchLocations } from '../api';
    
    let locationsPromise = $state(fetchLocations());
</script>

<div id="body">
	<Map
		style="height: 100vh; width: 100%; background-color: #262626;"
		options={{
			center: [30, 0],
			zoom: 5,
			minZoom: 4,
			maxZoom: 6,
		}}>
		<TileLayer 
            url={"https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"} 
            options = {{
                 attribution: "&copy; <a href='https://carto.com/'>Carto</a>",
                 noWrap : true
            }}/>
        {#await locationsPromise}
            <div>Loading...</div>
        {:then locations}
            {#each Object.entries(locations).map(([region, location]) => ({
                region,
                lat: location.Lat,
                lng: location.Long
            })) as location}
                <Marker latLng={[location.lat, location.lng]}>
                    <DivIcon options={{
                        className: 'emoji-pin',
                        html: '📍', 
                        iconSize: [30, 30],
                        iconAnchor: [15, 30]
                    }} />
                </Marker>
            {/each}
        {/await}    
	</Map>
</div>

<style>
#body {
    background-color: #262626;
    margin: 0;
    width: 100vw;
    height: 100vh;
    position: absolute;
    top: 0;
    left: 0;
    padding: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
        'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
        sans-serif;
}

</style>
